name: Build and Release

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        architecture: [x64]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      timeout-minutes: 10
      run: |
        sudo apt-get install -y opencl-headers ocl-icd-opencl-dev --no-install-recommends
    
    - name: Install Dependencies for Windows (Run windows.ps1)
      if: matrix.os == 'windows-latest'
      run: |
        pwsh -File "${GITHUB_WORKSPACE}/.github/workflows/windows.ps1"

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build the Project
      run: |
        cd build
        cmake --build . --config Release

    - name: Create GitHub Release
      id: release
      run: |
        # Generate a new version based on the Git tag or commit hash
        version=$(date +'%Y%m%d%H%M%S')
        gh release create "v$version" build/executable-name --title "Release $version" --notes "Automated release for commit $GITHUB_SHA"

    - name: Upload Executable to GitHub Release
      run: |
        # Upload the executable to the release
        gh release upload "v$version" build/executable-name
